config/routes.rb
Rails.application.routes.draw do
  resources :apts
  resources :appointments
  get 'pages/home' => 'pages/home', as: 'pages_home'

  get 'pages/appointment' => 'pages/appointment', as: 'pages_apt'

  get 'pages/about' => 'pages/about', as: 'pages_about'

  get 'pages/location' => 'pages/location', as: 'pages_location'

  get 'pages/services' => 'pages/services', as: 'pages_services'

  get 'reviews/index' => 'reviews/index', as: 'reviews_index'

  get 'apts' => 'apts', as: 'make_apts'

  devise_for :users
  resources :appoints
  get 'appoints' => 'appoints'
  resources :reviews
  root 'pages#home'
  get "/pages/:page" => "pages#show"

end

app/models/appoint.rb
#appointment.rb
 
class Appoint < ActiveRecord::Base
attr_accessible :date, :hour
 
validates :date,  :presence => true
validates :hour,  :presence => true,
                  :uniqueness => {:scope => :date}
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
end

app/models/apt.rb
class Apt < ActiveRecord::Base
end

app/models/review.rb
class Review < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/appointments_controller.rb
#app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

def index
  date_from_ajax = params[:matched_date]
  reduce = Appointment.where(:date => date_from_ajax)
  hour_on_date = reduce.collect {|x| x.hour}
  @new_dates = hour_on_date
  render :layout => false
end

def new
  @appointments = Appointment.create
    respond_to do |format|
      format.html
      format.js
      end
   end
 

def create
   @appointment = Appointment.create(params[:appointments])
    if @appointment.save
      redirect_to new_appointment_path
    else
      err = ''
      @appointment.errors.full_messages.each do |m|
      err << m
    end

      redirect_to new_appointment_path, :flash => { :alert => "#{err}, please try again" }
    end
  end
end

app/controllers/appoints_controller.rb
#app/controllers/appoints_controller.rb
class AppointsController < ApplicationController
 
  def index
    date_from_ajax = params[:matched_date]
    reduce = Appoint.where(:date => date_from_ajax)
    hour_on_date = reduce.collect {|x| x.hour}
    @new_dates = hour_on_date
    render :layout => false
  end
 
  def new
    @appoints = Appoint.create
      respond_to do |format|
        format.html
        format.js
     end
  end
  
 
  def create
     @appoint = Appoint.create(params[:appoints])
      if @appoint.save
        redirect_to new_appoint_path
      else
        err = ''
        @appoint.errors.full_messages.each do |m|
        err << m
      end
        redirect_to new_appoint_path, :flash => { :alert => "#{err}, please try again" }
      end
    end
 end

app/controllers/apts_controller.rb
class AptsController < ApplicationController
  before_action :set_apt, only: [:show, :edit, :update, :destroy]

  # GET /apts
  # GET /apts.json
  def index
    @apts = Apt.all
  end

  # GET /apts/1
  # GET /apts/1.json
  def show
  end

  # GET /apts/new
  def new
    @apt = Apt.new
  end

  # GET /apts/1/edit
  def edit
  end

  # POST /apts
  # POST /apts.json
  def create
    @apt = Apt.new(apt_params)

    respond_to do |format|
      if @apt.save
        format.html { redirect_to @apt, notice: 'Apt was successfully created.' }
        format.json { render :show, status: :created, location: @apt }
      else
        format.html { render :new }
        format.json { render json: @apt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apts/1
  # PATCH/PUT /apts/1.json
  def update
    respond_to do |format|
      if @apt.update(apt_params)
        format.html { redirect_to @apt, notice: 'Apt was successfully updated.' }
        format.json { render :show, status: :ok, location: @apt }
      else
        format.html { render :edit }
        format.json { render json: @apt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apts/1
  # DELETE /apts/1.json
  def destroy
    @apt.destroy
    respond_to do |format|
      format.html { redirect_to apts_url, notice: 'Apt was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apt
      @apt = Apt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def apt_params
      params.require(:apt).permit(:name, :time)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def appointment
  end

  def about
  end

  def location
  end

  def services
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:title, :body, :rating)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def header(text)
    content_for(:header) { text.to_s }
  end
end

app/helpers/appoint_helper.rb
module AppointHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/apts_helper.rb
module AptsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/appointments/_form.html.erb
<%= form_for(@appointment) do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!--<div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div> -->
  
  <div class="field form-group">
    <%= f.label :name, class: 'col-sm-2 control-label' %><br>
    <div class="col-sm-10">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class="field form-group">
    <%= f.label :location, class: 'col-sm-2 control-label' %><br>
    <div class="col-sm-10">
      <%= f.text_area :location, class: 'form-control' %>
    </div>
  </div>
  <div class="field form-group">
    <%= f.label :email, class: 'col-sm-2 control-label' %><br>
    <div class="col-sm-10">
      <%= f.text_area :email, class: 'form-control' %>
    </div>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form' %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<%= @new_dates %>

app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= render 'form' %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @appointment.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @appointment.location %>
</p>

<p>
  <strong>Email:</strong>
  <%= @appointment.email %>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>

app/views/apts/_form.html.erb
<%= form_for(@apt) do |f| %>
  <% if @apt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@apt.errors.count, "error") %> prohibited this apt from being saved:</h2>

      <ul>
      <% @apt.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name, class: 'col-sm-2 control-label' %><br>
    <div class="col-sm-10">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <!--<div class="field form-group">
    <%= f.label :time, class: 'col-sm-2 control-label' %><br>
    <div class="col-sm-10">
      <%= f.text_area :time, class: 'form-control' %>
    </div>
  </div> 
  -->
    <div class="field form-group">
    <%= f.label :time, class: 'col-sm-2 control-label' %><br>
    <div class="col-sm-10">
      <%= f.radio_button :time, 7 %>
      <%= f.label :time, "7:00 AM", :value => "0700" %>
      <%= f.radio_button :time, 10 %>
      <%= f.label :time, "10:00 AM", :value => "1000" %>
      <%= f.radio_button :time, 13 %>
      <%= f.label :time, "1:00 PM", :value => "1:00 PM" %>
      <%= f.radio_button :time, 17 %>
      <%= f.label :time, "4:00 PM", :value => "1700" %>

  <div class="actions form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/apts/edit.html.erb
<h1>Editing Apt</h1>

<%= render 'form' %>

<%= link_to 'Show', @apt %> |
<%= link_to 'Back', apts_path %>

app/views/apts/index.html.erb
<!DOCTYPE html>
<html>
<head>
<style>

body { background: #1C1C1C !important; }

h3{
  text-align: center;
  text-size: 25px;
}

h4{
  text-align: center;
  text-size: 25px;
}

a.button1{
     border: 0.5px solid;
     background-color: #4CAF50;
    padding: 15px 32px;
    border-radius: 25px;
    border-color: #4CAF50
    text-align: center;
    text-decoration: none;
    color: white;
    position:absolute;
    right:35%;
    top:30%;
    opacity: 0.8;
}

a.button2{
     border: 0.5px solid;
     background-color: #4CAF50;
    padding: 15px 32px;
    border-radius: 25px;
    border-color: #4CAF50
    text-align: center;
    text-decoration: none;
    color: white;
    position:absolute;
    right:55%;
    top:30%;
    opacity: 0.8;
}

a:hover {
   box-shadow: 3px 5px 3px #888888;
   text-shadow: 2px 2px 4px #888888;
   opacity: 1;
}

tr{
  align-items: middle !important;
}

</style>

<p id="notice"><%= notice %></p>
<!--
<h1>Listing Appointments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apts.each do |apt| %>
      <tr>
        <td><%= apt.name %></td>
        <td><%= apt.time %></td>
        <td><%= link_to 'Show', apt %></td>
        <td><%= link_to 'Edit', edit_apt_path(apt) %></td>
        <td><%= link_to 'Destroy', apt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
--><body>
     <font color="#FFF">
        <% if user_signed_in? %>
            
            <h3>Welcome</h3>
            <h3 align="center"><%= current_user.email %></h3>
            <!--<span class="caret"></span> -->
            <h4>Please create a new appointment!</h4>
            <%= link_to 'New Appointment', new_apt_path, class: 'btn btn-default' %>
        <% else %>
          <h4><font color="b2b2b2">You are not logged in. Please login or sign up.</h4>
          <div class"col-md-4 center-block">
          <a class = "button1" href="http://localhost:3000/users/sign_in" class="button">log In</a>
          <a class = "button2" href="http://localhost:3000/users/sign_up" class="button">sign Up</a>
          
          </div>
        <% end %>
        </font>
</body>

app/views/apts/new.html.erb
<h1>New Appointment</h1>

<%= render 'form' %>

<%= link_to 'Back', apts_path %>

app/views/apts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @apt.name %>
</p>

<p>
  <strong>Time:</strong>
  <%= @apt.time %>
</p>

<%= link_to 'Edit', edit_apt_path(@apt) %> |
<%= link_to 'Back', apts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Classic Auto</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


</head>
<body  bgcolor = "#1C1C1C">
  <%= render 'shared/navigation' %>
    <h1 font size = "5" color = "#FFF"><p class="notice"><%= notice %></p></h1>
    <h1 font size = "5" color = "#FFF"><p class="alert"><%= alert %></p> </h1>
          <!-- <h1>Classic Auto</h1> -->
          <!--<%= image_tag("Logo_1.png", :alt => "Logo", :size => "200x76") %> -->
          <%= yield %>
    

</body>
</html>

app/views/pages/about.html.erb
<!DOCTYPE 
<html>
<head>
<style>

a{
  text-decoration: none;
}

 body { background: #1C1C1C !important; }

p.center-justified{
  width: 300px;
  
  text-align: justify;
  -moz-text-align-last: center;
    text-align-last: center;
}
a:hover {
  text-shadow: 2px 2px 4px #888888;
}

</style>
</head>

<body bgcolor = "#1C1C1C" !important>

<font face="century gothic" color="#FFFFF">

<font face="ar decode" color="#4B4B4B" size="7"><h1 align="center">About Us</h1></font>     

<p>Classic Auto is a family owned auto body repair shop in the Silicon Valley. Our auto body shop was created with the customers in mind and we specialize in repairing their car problems.We understand the distinct challenges presented when having car issues therefore our philosophy to make everyone’s dream car a reality.
</p>

</font>
</body>
</html>

app/views/pages/appoint.html.erb
<link rel="stylesheet" href="/jquery-ui-1.8.17.custom.css">

<div id="datepicker"></div>

<div id='hour_picker'>
<table border="1">
<tr>
<th class = 'selected_date'></th>
</tr>
<tr class = 'cal_table'>
<td type ="button" onclick = "nextPage('0700', this.id)" class = '0700' id = "7:00 am">7:00 am</td>
</tr>
<tr class = "cal_table2">
<td type ="button" onclick = "nextPage('0800', this.id)" class = '0800' id = "8:00 am">8:00 am</td>
</tr>
<tr class = "cal_table">
<td type ="button" onclick = "nextPage('0900', this.id)" class = '0900' id = "9:00 am">9:00 am</td>
</tr>
<tr class = "cal_table2">
<td type ="button" onclick = "nextPage('1000', this.id)" class = '1000' id = "10:00 am">10:00 am</td>
</tr>
<tr class = "cal_table" id = '5'>
<td type ="button" onclick = "nextPage('1100', this.id)" class = '1100' id = "11:00 am">11:00 am</td>
</tr>
<tr class = "cal_table2" id = '6'>
<td type ="button" onclick = "nextPage('1200', this.id)" class = '1200' id = "12:00 pm">12:00 pm</td>
</tr>
<tr class = "cal_table" id = '7'>
<td type ="button" onclick = "nextPage('1300', this.id)" class = '1300' id = "1:00 pm">1:00 pm</td>
</tr>
<tr class = "cal_table2" id = '8'>
<td type ="button" onclick = "nextPage('1400', this.id)" class = '1400' id = "2:00 pm">2:00 pm</td>
</tr>
<tr class = "cal_table2" id = '8'>
<td type ="button" onclick = "nextPage('1500', this.id)" class = '1500' id = "3:00 pm">3:00 pm</td>
</tr>
<tr class = "cal_table2" id = '8'>
<td type ="button" onclick = "nextPage('1600', this.id)" class = '1600' id = "4:00 pm">4:00 pm</td>
</tr>
<tr class = "cal_table2" id = '8'>
<td type ="button" onclick = "nextPage('1700', this.id)" class = '1700' id = "5:00 pm">5:00 pm</td>
</tr>
<tr class = "cal_table2" id = '8'>
<td type ="button" onclick = "nextPage('1800', this.id)" class = '1800' id = "6:00 pm">6:00 pm</td>
</tr>

<tr class = "cal_table3">
<td class = 'cal_previous'><form method='link' action="/appoints/new"><button class='btn'>back</button></form></td>
</tr>
</table>
</div>

<div id='cal_previous2'><button class='btn' onclick='prevPage();'>back</button></div><br />

            <div id="appoint_form">
              <%%= form_tag("/appoints", :method => "post") do %>
                            
                            <br />
                            <label for="appoints_date">scheduled date</label><br /><br />
                            <div id = "final_date"><h2></h2></div>
                            <input id="schedules_date" name="appoints[date]" type="hidden" />
                            <br />
                            <br />
                            
                            <label for="appoints_hour">scheduled hour</label><br /><br />
                            <div id = "final_hour"><h2></h2></div>
                            <input id="appoints_hour" name="appoints[hour]" type="hidden" />
                            <br />
                            <br />

                            <input type="submit" name="btn" value="Submit" class = 'btn' id="subData" style="display:none;">
                            
                             <%%= submit_tag("Submit") %>
               <%% end %>

</div>
      
<div id = "hidden_hour_div"></div>  

  <script src="/jquery.ui.widget.min.js"></script>
  <script src="/jquery.ui.datepicker.min.js"></script>
  <script src="/appoint.js"></script>

app/views/pages/appointment.html.erb
<!DOCTYPE html>
<html>
<head>


</head>
<body>
  <section class="loginform cf">
    <form name="login" action="index_submit" method="get" accept-charset="utf-8">
      <ul>
        <li>
          <label for="usermail">Email</label>
          <input type="email" name="usermail" placeholder="yourname@email.com" required>
        </li>
        <li>
          <label for="password">Password</label>
          <input type="password" name="password" placeholder="password" required></li>
        <li>
          <input type="submit" value="Login">
        </li>
      </ul>
    </form>
  </section>
</body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
<head>
<style>

div.text{
    font-family: "Harlow Solid Italic";
    padding-top:5px; 
    text-align: center;
    font-size: 90px;
    font-weight: bolder;
    color: #000;
    right:50%;
    top:50%;
    -webkit-animation: fadein 5s;
    text-shadow: 2px 2px 4px #888888;
}

body {
    background: url(http://i.imgur.com/YabWLiU.jpg?1);
    width:1330px;
    height:768px;
    background-position: center; 
}

a.button{
     border: 0.5px solid;
     background-color: #4CAF50;
    padding: 15px 32px;
    border-radius: 25px;
    border-color: #4CAF50
    text-align: center;
    text-decoration: none;
    color: white;
    position:absolute;
    right:45%;
    top:50%;
    opacity: 0.8;
}

a:hover {
   box-shadow: 3px 5px 3px #888888;
   text-shadow: 2px 2px 4px #888888;
   opacity: 1;
}

k { image-align: center }

</style>
</head>
<body>
    <div class = "text"><p><font face="Harlow Solid" font size = "7">Classic Auto Services</font></p></div>
    <a href="http://localhost:3000/pages/services" class="button">Services</a>


</body>
</html>

app/views/pages/html.erb
class PagesController < ApplicationController
  def show
    render template: "pages/#{params[:page]}"
  end
end

app/views/reviews/_form.html (copy).erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.number_field :rating %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<!--  app/views/reviews/index.html.erb -->
<style type="text/css">
   body { background: lightgrey !important; }

</style>>

<body>
<ul class="nav nav-tabs" role="tablist" bgcolor= #1C1C1C>
  <li class="active"><%= link_to 'View reviews', reviews_path %></li>
  <li><%= link_to 'New review', new_review_path %></li>
</ul>

<p id="notice"><%= notice %></p>

<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Listing Reviews</div>

  <!-- Table -->
  <table class="table">
    <thead>
      <tr>
        
        <th>Title</th>
        <th>Body</th>
        <th>Rating</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.title %></td>
        <td><%= review.body %></td>
        <td><%= review.rating %></td>
        <td><%= link_to 'Show', review, class: 'btn btn-default btn-xs' %></td>
        <td><%= link_to 'Edit', edit_review_path(review), class: 'btn btn-default btn-xs' %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default btn-xs' %></td>
      </tr>
    <% end %>
  </tbody>
  </table>
</div>
<%= link_to new_review_path, class: 'btn btn-default' do %>
  <i class="glyphicon glyphicon-plus"></i> New Review
<% end %>

<!--<% content_for :top_content do %>
  <div class="jumbotron">
    <div class="container">
      <h1>Welcome!</h1>
      <p>Register to get started.</p>
      <p>
        <%= link_to 'Register', new_user_registration_path, class: 'btn btn-default btn-lg' %>
      </p>
    </div>
  </div>
<% end %>
-->
</body>

app/views/reviews/new.html.erb
<!--  app/views/reviews/new.html.erb -->
<style type="text/css">
   body { background: lightgrey !important; }

</style>

<body>
<ul class="nav nav-tabs" role="tablist">
  <li><%= link_to 'View reviews', reviews_path %></li>
  <li class="active"><%= link_to 'New review', new_review_path %></li>
</ul>

<h2>New Review</h2>

<%= render 'form' %>

<%= link_to 'Back', reviews_path, class: 'btn btn-default' %>
</body>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @review.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @review.body %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>

<%= link_to 'Edit', edit_review_path(@review), class: 'btn btn-default' %> |
<%= link_to 'Back', reviews_path, class: 'btn btn-default' %>

app/views/shared/_navigation.html.erb
<!-- app/views/shared/_navigation.html.erb -->

<script src="http://www.google.com/jsapi"></script>
<script>
 google.load("jquery", "1");
 google.load("jqueryui", "1");
</script>
<script>
$(document).ready(function()
{
 $('body').hide().fadeIn(2000); 
});
</script>


<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <!-- <a class="navbar-brand" href="/">Welcome to Classic Auto</a> -->
      <%= link_to 'Classic Auto', root_path, class: 'navbar-brand' %>
    </div>
    
    <div id="navbar">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Appointment', apts_path %></li>
        <li><%= link_to 'Locations', pages_location_path %></li>
        <li><%= link_to 'Services', pages_services_path %></li>
        <li><%= link_to 'About Us', pages_about_path %></li>
        <li><%= link_to 'Ratings', reviews_index_path %></li>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <%= current_user.email %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Profile', edit_user_registration_path %></li>
              <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Log In', new_user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>